### ISSUE TITLE
Add "ATTRIBUTES" functionality

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/garage-roadmap#27]
See https://senzing.atlassian.net/browse/GDEV-3917

Member of https://github.com/senzing-garage/garage-roadmap/issues/5

**Comment by barrycaceres** [comment]
1) `SZ_ENTITY_INCLUDE_RECORD_FEATURE_IDS` → `SZ_ENTITY_INCLUDE_RECORD_FEATURES`

Flag was renamed.  Same old flag value (same bit).  Still only applies to “entity” retrieval calls (e.g.: `getEntity()` `searchByAttributes()`, `exportJSON()`, `findPath()`, `findNetwork()` and `why()`) even though it modifies the record section.  This creates references from the record section back to the entity features so you can tell which records contributed to which features.

**NOTE**: JSON format is likely still the same but it may change to be broken down by feature like the new flags (according to @Brian Macy )

2) `SZ_ENTITY_INCLUDE_RECORD_FEATURE_DETAILS` and `SZ_ENTITY_INCLUDE_RECORD_FEATURE_STATS`

These are new flags.  They apply to all “entity” retrieval calls as above, but ALSO apply to `getRecord()` calls.  These provide the `FEATURES` JSON segment at the `RECORD` level in the JSON that in the past has only existed at the `ENTITY` level of the JSON .  The feature details is illustrated in the Jira description, but the `FEATURE_STATS` will appear as it does for the `SZ_ENTITY_INCLUDE_FEATURE_STATS` – in each case we see the features in detail contributed by a record at the record level.

**IMPORTANT NOTE 1**: These flags modify the search criteria part of the JSON response on `searchByAttribute()` as well in that you will see feature details and/or statistics on the hypothetical search record that acts as the search criteria.

**IMPORTANT NOTE 2**: These flags interact with the `SZ_ENTITY_INCLUDE_INTERNAL_FEATURES` flag which was previously **NOT APPLICABLE** to `getRecord()` calls.  However, since these flags interact with **SZ_ENTITY_INCLUDE_INTERNAL_FEATURES** that flag is **NOW APPLICABLE** to `getRecord()` calls, changing the behavior of that flag.
